modLoader = "javafml"
loaderVersion = "[32,)"
license = "Apache 2.0"

[[mods]]
    modId = "restart4server"
    version = "${file.jarVersion}"
    displayName = "Restart4Server"
    authors = "DenisD3D"
    description = '''

    '''

[[dependencies.restart4server]]
    modId = "forge"
    mandatory = true
    versionRange = "[32,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.restart4server]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.1,1.17)"
    ordering = "NONE"
    side = "BOTH"
